# Enable all cops by default
AllCops:
  NewCops: enable 

Layout/AlignHash:
  EnforcedStyle: hash_roots

Layout/IndentationConsistency:
  Enabled: true

Layout/DoubleQuotes:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: consistent
  IndentationWidth: 2

Layout/PrivateMethodIndentation:
  Enabled: true
  IndentationWidth: 2

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Metrics/LineLength:
  Max: 80
  ExcludedMethods: []
  ExcludedPatterns: []

Metrics/AbcSize:
  Max: 15

Style/Documentation:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: true
